<?php namespace ProcessWire;

class MarkupModularUI extends WireData implements Module
{

	public static function getModuleInfo()
	{
		return array(
			'title' => 'MarkupModularUI',
			'version' => 001,
			'summary' => 'A Hierarchical Model-View-Controller (HMVC) Framework for building modular, nestable graphical user interfaces in ProcessWire. Usage: Create a /site/templates/ui folder and set all of your templates to use main.php for output.',
			'singular' => true,
			'autoload' => true,
			'installs' => array(),
			'requires' => array(),
			'icon' => 'clone',
		);
	}

	public function __construct() {}

	public function init() {}

	public function ready() {
		if($this->page->template == 'admin') return;

		include(dirname(__FILE__) . '/UI.php'); // Load UI base class

		// Autoload UI subclasses when they're called
		spl_autoload_register(function ($class) {
			$nameParts = explode('\\', $class);
			$className = array_pop($nameParts); // Get the class name without the namespace
			$uiName = substr($className, 0, -2); // Remove "UI" from the class name to get the name of the user interface
			$file = wire('config')->paths->templates . "ui/$uiName/$className.php";
			if(is_file($file)) include $file;
		});
	}

	public function install() {}

	public function uninstall() {}

}